# Generated by Django 5.1.5 on 2025-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trader', 'Trader'), ('representative', 'Representative'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
