# Generated by Django 5.1.7 on 2025-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('job seeker', 'Job Seeker')], default='job seeker', max_length=20),
        ),
    ]
